### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by ms5573** [prrao87/fine-grained-sentiment#2]
Really enjoy working through your tutorial! I tried to apply my own data to the Flair model but get a run time error: "cuda runtime error (2) : out of memory" when it switches from epoch 1 to epoch 2. I have a relatively powerful GPU (2080 TI) with 11GB so I was a bit surprised to see this error. I tried to reduce the size of the training data set but no luck. Any suggestions how that could be resolved? 

Any help would be appreciated. Thank you!

**Comment by prrao87** [comment]
Glad it helped! Regarding your out of memory error, it's an issue I've myself faced in the past when using Flair on custom datasets - the thing to watch out for is cases where certain documents are **much** longer than others. With this imbalanced document size, there can be an issue packing the token IDs onto the GPU. Diagnosing which exactly is the offending document can be tedious, so it helps to carefully study the data you're working with during preprocessing.

In addition to this document size imbalance, if you're stacking BERT embeddings with Flair, you'll also have to watch out when tokenizing long sequences of length > 512. This is a [documented issue](https://github.com/flairNLP/flair/issues/831) that can be resolved by using the pytorch-transformers tokenizer instead (I believe they just released their new `tokenizers` library).

**Comment by ms5573** [comment]
Thanks a lot Prashanth! I will incorporate your suggestions. Looking forward to any more of your work on NLP or ML in general.
