### ISSUE TITLE
pip install requirements.txt fail

### ISSUE THREAD

**Issue by YuhaoT** [prrao87/fine-grained-sentiment#5]
when I used `pip install -r requirements.txt`, it gave me an error below

Could not find a version that satisfies the requirement torch==1.1.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
No matching distribution found for torch==1.1.0

May I use torch version greater than 1.1.0?

**Comment by czhao028** [comment]
I had this same issue - how did you solve it?

**Comment by prrao87** [comment]
@czhao028 the code in this repo was run/tested on Python 3.6, and if you're using one of the more recent python versions, the version numbers mentioned in the requirements.txt file are not guaranteed to work. Particularly with PyTorch, newer versions of Python may only support versions newer than 1.1.0, so I recommend using the code in this repo as a starting point for building/training your own transformer models in a more recent version of Python/PyTorch. Hope this helps!
